"""added 3-way authentication method

Revision ID: 1422dd539509
Revises: 15b449474a9d
Create Date: 2026-05-28 17:40:32.868568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1422dd539509'
down_revision: Union[str, Sequence[str], None] = '15b449474a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_expires')
    op.drop_column('users', 'mfa_code')
    # ### end Alembic commands ###
