"""add_full_quest_details

Revision ID: 29d58cac2ab5
Revises: cfb8edcabf92
Create Date: 2026-05-16 00:26:15.324906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d58cac2ab5'
down_revision: Union[str, Sequence[str], None] = 'cfb8edcabf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('author', sa.String(), nullable=True))
    op.add_column('quests', sa.Column('status', sa.String(), nullable=True))
    op.add_column('quests', sa.Column('daytime', sa.String(), nullable=True))
    op.add_column('quests', sa.Column('weather', sa.String(), nullable=True))
    op.add_column('quests', sa.Column('season', sa.String(), nullable=True))
    op.alter_column('quests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('quests', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quests', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('quests', 'season')
    op.drop_column('quests', 'weather')
    op.drop_column('quests', 'daytime')
    op.drop_column('quests', 'status')
    op.drop_column('quests', 'author')
    # ### end Alembic commands ###
