"""add_cost_to_quests

Revision ID: cfb8edcabf92
Revises: 03945bebca70
Create Date: 2026-05-15 23:46:50.952066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb8edcabf92'
down_revision: Union[str, Sequence[str], None] = '03945bebca70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('cost', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'cost')
    # ### end Alembic commands ###
