"""add_user_timeout_and_ban

Revision ID: d988e4f1bff9
Revises: 1cf39b4657da
Create Date: 2026-05-27 21:46:12.727486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd988e4f1bff9'
down_revision: Union[str, Sequence[str], None] = '1cf39b4657da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('timeout_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timeout_until')
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
